CREATE TABLE address (
  ADDRESS_ID BIGINT(50) NOT NULL AUTO_INCREMENT,
  USER_ADDRESS VARCHAR(100) NULL,
  STREET VARCHAR(50) NULL,
  CITY VARCHAR(50) NULL,
  STATE VARCHAR(50) NULL,
  ZIP VARCHAR(10) NULL,
  userId BIGINT NOT NULL,
  PRIMARY KEY (ADDRESS_ID)
) ;

CREATE TABLE user_registration (
   id INT(100) NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(100) NOT NULL,
   BIRTH_DATE VARCHAR(50) DEFAULT NULL,
   GENDER VARCHAR(10) DEFAULT NULL,
   NATIONALITY VARCHAR(50) DEFAULT NULL,
   WEBSITE VARCHAR(100) NOT NULL,
   NO_OF_SMS INT(10) NOT NULL,
   EMAIL VARCHAR(100) NOT NULL,
   PASSWORD VARCHAR(100) NOT NULL,
   PHONE BIGINT(100) NOT NULL,
   CREATION_DATE DATE NOT NULL,
   AUTHENTICATED VARCHAR(5) NOT NULL,
   lastName VARCHAR(10) DEFAULT NULL,
   aboutMe VARCHAR(100) DEFAULT NULL,
   imageInByte BLOB DEFAULT NULL,
  PRIMARY KEY(id)
  );

SELECT * FROM user_registration;

SELECT * FROM address;

SELECT * FROM contacts;

SELECT * FROM user_otp;

SELECT * FROM profileImage;

DELETE FROM profileImage WHERE userId=1;
CREATE TABLE profileImage(
  `userId` INT(11) NOT NULL,
  `photo` MEDIUMBLOB,
  PRIMARY KEY (`userId`)
) ENGINE=INNODB DEFAULT CHARSET=latin1

CREATE TABLE comments(
  commentsId INT(20)NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
   website VARCHAR(50) DEFAULT NULL,
   subjects VARCHAR(50) DEFAULT NULL,
    comments VARCHAR(100) DEFAULT NULL,
    parentsId INT(20),
  PRIMARY KEY (commentsId)
) ;

CREATE TABLE reply(
  replyId INT(20)NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  comments VARCHAR(100) DEFAULT NULL,
  commentsId INT(20),
  PRIMARY KEY (replyId)
);